### ISSUE TITLE
Errors installing paramiko

### ISSUE THREAD

**Issue by smaboshe** [guilro/trellis-backup-role#11]
Hello!

I have just updated to using the Ansible 2.4 compatible version of Trellis. During `vagrant up --provision #--debug`, I get the following error:

```
TASK [trellis-backup : Ensure paramiko is installed] ***************************
System info:
  Ansible 2.4.0.0; Vagrant 2.0.0; Linux
  Trellis at "Normalize `apt` tasks"
---------------------------------------------------
stdout: Collecting paramiko
  Using cached paramiko-2.3.1-py2.py3-none-any.whl
Collecting pynacl>=1.0.1 (from paramiko)
  Using cached PyNaCl-1.1.2-cp27-cp27mu-manylinux1_x86_64.whl
Collecting cryptography>=1.5 (from paramiko)
  Using cached cryptography-2.1-cp27-cp27mu-manylinux1_x86_64.whl

:stderr: Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 209, in
main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 328,
in run
    wb.build(autobuilding=True)
  File "/usr/lib/python2.7/dist-packages/pip/wheel.py", line 748, in build
    self.requirement_set.prepare_files(self.finder)
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 360, in
prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 647, in
_prepare_file
    set(req_to_install.extras) - set(dist.extras)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line
2670, in extras
    return [dep for dep in self._dep_map if dep]
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line
2713, in _dep_map
    self.__dep_map = self._compute_dependencies()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line
2723, in _compute_dependencies
    reqs.extend(parse_requirements(req))
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line
2781, in parse_requirements
    yield Requirement(line)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line
2790, in __init__
    raise RequirementParseError(str(e))
RequirementParseError: Invalid requirement, parse error at "'; python'"
You are using pip version 8.1.1, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

fatal: [default]: FAILED! => {"changed": false, "cmd": "/usr/bin/pip2 install paramiko", "failed": true}

RUNNING HANDLER [common : reload nginx] ****************************************
changed: [default]

RUNNING HANDLER [common : perform nginx reload] ********************************
changed: [default]
        to retry, use: --limit @/home/silumesii/example.com/trellis/dev.retry

PLAY RECAP *********************************************************************
default                    : ok=104  changed=7    unreachable=0    failed=1   

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
```

Help?

**Comment by jillro** [comment]
Paramiko is not anymore installed with last version.
